/**
 * Frontend Assignment
 * Use this backend server for development of your frontend asignment. No API key is required to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTaskDtoFields } from './createTaskDtoFields';

export interface CreateTaskDto {
  /**
   * Name of the task
   */
  name: string;
  /**
   * Type of the task
   */
  type: CreateTaskDto.TypeEnum;
  fields: CreateTaskDtoFields;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace CreateTaskDto {
  export type TypeEnum = 'wash-dishes' | 'vacuum-clean';
  export const TypeEnum = {
    WashDishes: 'wash-dishes' as TypeEnum,
    VacuumClean: 'vacuum-clean' as TypeEnum,
  };
}
