/**
 * Frontend Assignment
 * Use this backend server for development of your frontend asignment. No API key is required to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VacuumCleanFields {
  /**
   * How will be vacuum cleaning
   */
  who: string;
  /**
   * Which room will be vacuum cleaned
   */
  room: string;
}
